openapi: 3.1.0
info:
  title: p4pa-pu-sil
  description: Api and Models
  version: "1.0.0"
paths:
  /api/v1/greet:
    get:
      summary: "Hello World"
      description: "Sample endpoint that return greetings"
      responses:
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hello, World!"
        '500':
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal Server Error"
security:
  - BearerAuth: []
components:
  schemas:
    PuSilErrorDTO:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          enum:
            - PU_SIL_BAD_REQUEST
            - PU_SIL_GENERIC_ERROR
        message:
          type: string
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
