package it.gov.pagopa.pu.sil.util;

public class ErrorCodeConstants {
  private ErrorCodeConstants() {}

  public static final String ERROR_CODE_ASSESSMENT_NOT_FOUND = "ASSESSMENT_NOT_FOUND";
  public static final String ERROR_CODE_NOTICE_NOT_FOUND = "NOTICE_NOT_FOUND";
  public static final String ERROR_CODE_RECEIPT_NOT_FOUND = "RECEIPT_NOT_FOUND";

  public static final String ERROR_CODE_INVALID_ACCESS_TOKEN = "INVALID_ACCESS_TOKEN";
  public static final String ERROR_CODE_INVALID_BALANCE = "INVALID_BALANCE";
  public static final String ERROR_CODE_INVALID_DEBT_POSITION_TYPE_ORG_CODE = "INVALID_DEBT_POSITION_TYPE_ORG_CODE";
  public static final String ERROR_CODE_INVALID_DEBT_POSITION_TYPE_ORG_STATUS = "INVALID_DEBT_POSITION_TYPE_ORG_STATUS";
  public static final String ERROR_CODE_INVALID_INGESTION_FLOW_FILE_LEGACY_TYPE = "INVALID_INGESTION_FLOW_FILE_LEGACY_TYPE";
  public static final String ERROR_CODE_INVALID_CALLBACK_URL = "INVALID_CALLBACK_URL";

  public static final String ERROR_CODE_XML_MARSHALLING_ERROR = "XML_MARSHALLING_ERROR";
  public static final String ERROR_CODE_XML_UNMARSHALLING_ERROR = "XML_UNMARSHALLING_ERROR";

  public static final String ERROR_CODE_ACTUALIZATION_ERROR = "ACTUALIZATION_ERROR";
  public static final String ERROR_CODE_GENERATE_NOTICE_ERROR = "GENERATE_NOTICE_ERROR";
  public static final String ERROR_CODE_RECEIPT_ERROR = "RECEIPT_ERROR";

  public static final String ERROR_CODE_INVALID_PAYMENT_STATUS = "INVALID_PAYMENT_STATUS";
  public static final String ERROR_CODE_PAYMENT_NOT_FOUND = "PAYMENT_NOT_FOUND";
  public static final String ERROR_CODE_PAYMENT_NOT_NOTIFIED = "PAYMENT_NOT_NOTIFIED";

  public static final String ERROR_CODE_UNSUPPORTED_REGISTRY_EVENT_TYPE = "UNSUPPORTED_REGISTRY_EVENT_TYPE";

}
