package it.gov.pagopa.pu.sil.util;

public class ErrorCodeConstants {
  private ErrorCodeConstants() {}

  public static final String ERROR_CODE_ASSESSMENT_NOT_FOUND = "ASSESSMENT_NOT_FOUND";
  public static final String ERROR_CODE_NOTICE_NOT_FOUND = "NOTICE_NOT_FOUND";
  public static final String ERROR_CODE_RECEIPT_NOT_FOUND = "RECEIPT_NOT_FOUND";
  public static final String ERROR_CODE_DEBT_POSITION_NOT_FOUND = "DEBT_POSITION_NOT_FOUND";
  public static final String ERROR_CODE_INSTALLMENT_NOT_FOUND = "INSTALLMENT_NOT_FOUND";
  public static final String ERROR_CODE_PAYMENT_REPORTING_NOT_FOUND = "PAYMENT_REPORTING_NOT_FOUND";

  public static final String ERROR_CODE_MISSING_IUV = "MISSING_IUV";
  public static final String ERROR_CODE_MISSING_DEBT_POSITION_TYPE_ORG = "MISSING_DEBT_POSITION_TYPE_ORG";
  public static final String ERROR_CODE_MISSING_TAXONOMY_CATEGORY = "MISSING_TAXONOMY_CATEGORY";
  public static final String ERROR_CODE_MISSING_REMITTANCE_INFORMATION = "MISSING_REMITTANCE_INFORMATION";
  public static final String ERROR_CODE_MISSING_DEBTOR = "MISSING_DEBTOR";
  public static final String ERROR_CODE_MISSING_DUE_DATE = "MISSING_DUE_DATE";
  public static final String ERROR_CODE_MISSING_ID_SESSION = "MISSING_ID_SESSION";
  public static final String ERROR_CODE_MISSING_ID_SESSION_CARRELLO = "MISSING_ID_SESSION_CARRELLO";
  public static final String ERROR_CODE_INVALID_PARAMETER_COMBINATION = "INVALID_PARAMETER_COMBINATION";

  public static final String ERROR_CODE_INVALID_ACCESS_TOKEN = "INVALID_ACCESS_TOKEN";
  public static final String ERROR_CODE_INVALID_BALANCE = "INVALID_BALANCE";
  public static final String ERROR_CODE_INVALID_DEBT_POSITION_TYPE_ORG_CODE = "INVALID_DEBT_POSITION_TYPE_ORG_CODE";
  public static final String ERROR_CODE_INVALID_DEBT_POSITION_TYPE_ORG_STATUS = "INVALID_DEBT_POSITION_TYPE_ORG_STATUS";
  public static final String ERROR_CODE_INVALID_INGESTION_FLOW_FILE_LEGACY_TYPE = "INVALID_INGESTION_FLOW_FILE_LEGACY_TYPE";
  public static final String ERROR_CODE_INVALID_CALLBACK_URL = "INVALID_CALLBACK_URL";
  public static final String ERROR_CODE_INVALID_IUV = "INVALID_IUV";
  public static final String ERROR_CODE_INVALID_IUD = "INVALID_IUD";
  public static final String ERROR_CODE_INVALID_DEBT_POSITION_TYPE_ORG = "INVALID_DEBT_POSITION_TYPE_ORG";
  public static final String ERROR_CODE_INVALID_FILE_VERSION = "INVALID_FILE_VERSION";
  public static final String ERROR_CODE_INVALID_DATE_FILTER_COMBINATION = "INVALID_DATE_FILTER_COMBINATION";
  public static final String ERROR_CODE_INVALID_DATE_FILTER_INTERVAL = "INVALID_DATE_FILTER_INTERVAL";
  public static final String ERROR_CODE_INVALID_ORGANIZATION = "INVALID_ORGANIZATION";
  public static final String ERROR_CODE_INVALID_ORGANIZATION_STATUS = "INVALID_ORGANIZATION_STATUS";
  public static final String ERROR_CODE_INVALID_IBAN = "INVALID_IBAN";
  public static final String ERROR_CODE_INVALID_AMOUNT = "INVALID_AMOUNT";
  public static final String ERROR_CODE_INVALID_CENTS_AMOUNT = "INVALID_CENTS_AMOUNT";
  public static final String ERROR_CODE_INVALID_TAXONOMY_CATEGORY = "INVALID_TAXONOMY_CATEGORY";
  public static final String ERROR_CODE_INVALID_LEGACY_PAYMENT_METADATA = "INVALID_LEGACY_PAYMENT_METADATA";
  public static final String ERROR_CODE_INVALID_FULLNAME = "INVALID_FULLNAME";
  public static final String ERROR_CODE_INVALID_EMAIL = "INVALID_EMAIL";
  public static final String ERROR_CODE_INVALID_VAT_CODE = "INVALID_VAT_CODE";
  public static final String ERROR_CODE_INVALID_DUE_DATE = "INVALID_DUE_DATE";
  public static final String ERROR_CODE_INVALID_ID_SESSION = "INVALID_ID_SESSION";
  public static final String ERROR_CODE_INVALID_ADDRESS = "INVALID_ADDRESS";
  public static final String ERROR_CODE_INVALID_COUNTRY = "INVALID_COUNTRY";
  public static final String ERROR_CODE_INVALID_PROVINCE = "INVALID_PROVINCE";
  public static final String ERROR_CODE_INVALID_POSTAL_CODE = "INVALID_POSTAL_CODE";
  public static final String ERROR_CODE_INVALID_STREET_NUMBER = "INVALID_STREET_NUMBER";
  public static final String ERROR_CODE_INVALID_REQUEST_TOKEN = "INVALID_REQUEST_TOKEN";
  public static final String ERROR_CODE_INVALID_ACTION = "INVALID_ACTION";
  public static final String ERROR_CODE_INVALID_STAMP = "INVALID_STAMP";
  public static final String ERROR_CODE_INVALID_XML = "INVALID_XML";
  public static final String ERROR_CODE_INVALID_CART_SIZE = "INVALID_CART_SIZE";
  public static final String ERROR_CODE_INVALID_MULTI_PARAMS_REQUEST = "INVALID_MULTI_PARAMS_REQUEST";

  public static final String ERROR_CODE_XML_MARSHALLING_ERROR = "XML_MARSHALLING_ERROR";
  public static final String ERROR_CODE_XML_UNMARSHALLING_ERROR = "XML_UNMARSHALLING_ERROR";

  public static final String ERROR_CODE_ACTUALIZATION_ERROR = "ACTUALIZATION_ERROR";
  public static final String ERROR_CODE_GENERATE_NOTICE_ERROR = "GENERATE_NOTICE_ERROR";
  public static final String ERROR_CODE_RECEIPT_ERROR = "RECEIPT_ERROR";
  public static final String ERROR_CODE_CHECKOUT_URL_ERROR = "CHECKOUT_URL_ERROR";
  public static final String ERROR_CODE_SYNC_ERROR = "SYNC_ERROR";
  public static final String ERROR_CODE_SYSTEM_ERROR = "SYSTEM_ERROR";

  public static final String ERROR_CODE_INVALID_PAYMENT_STATUS = "INVALID_PAYMENT_STATUS";
  public static final String ERROR_CODE_PAYMENT_NOT_FOUND = "PAYMENT_NOT_FOUND";
  public static final String ERROR_CODE_PAYMENT_NOT_NOTIFIED = "PAYMENT_NOT_NOTIFIED";

  public static final String ERROR_CODE_DUPLICATED_IUD = "DUPLICATED_IUD";

  public static final String ERROR_CODE_UNSUPPORTED_REGISTRY_EVENT_TYPE = "UNSUPPORTED_REGISTRY_EVENT_TYPE";

  public static final String ERROR_CODE_IMMUTABLE_FIELD = "IMMUTABLE_FIELD";
  public static final String ERROR_CODE_DEBT_POSITION_TYPE_ORG_UNAUTHORIZED = "DEBT_POSITION_TYPE_ORG_UNAUTHORIZED";

  public static final String ERROR_CODE_TOO_MANY_TRANSFERS_FOR_INSTALLMENT = "TOO_MANY_TRANSFERS_FOR_INSTALLMENT";

  public static final String ERROR_CODE_INSTALLMENT_ALREADY_EXISTS = "INSTALLMENT_ALREADY_EXISTS";
  public static final String ERROR_CODE_DEBT_POSITION_ALREADY_EXISTS = "DEBT_POSITION_ALREADY_EXISTS";

  public static final String ERROR_CODE_ANONYMOUS_DEBTOR_NOT_SUPPORTED = "ANONYMOUS_DEBTOR_NOT_SUPPORTED";
  public static final String ERROR_CODE_INSTALLMENT_TRANSFER_CONFIGURATION_NOT_SUPPORTED = "INSTALLMENT_TRANSFER_CONFIGURATION_NOT_SUPPORTED";

  public static final String ERROR_CODE_INSTALLMENT_NOT_PAID = "INSTALLMENT_NOT_PAID";
  public static final String ERROR_CODE_INSTALLMENT_EXPIRED = "INSTALLMENT_EXPIRED";
  public static final String ERROR_CODE_INSTALLMENT_NOT_PAYABLE = "INSTALLMENT_NOT_PAYABLE";

  public static final String ERROR_CODE_MULTIBENEFICIARY_THRESHOLD = "MULTIBENEFICIARY_THRESHOLD";
}
