server:
  http: "\${SERVER_PORT:8080}"

spring:
  application:
    name: ${artifactId}
    version: ${version}
  jmx.enabled: true
  threads:
    virtual:
      enabled: "\${VIRTUAL_THREADS_ENABLED:true}"
  cloud:
    function:
      definition: registryProducer
    stream:
      binders:
        kafka-registry-producer:
          type: kafka
          environment:
            spring.cloud.stream.kafka.binder:
              brokers: "\${KAFKA_BINDER_BROKER:}"
              configuration:
                sasl.jaas.config: "\${KAFKA_REGISTRIES_PRODUCER_SASL_JAAS_CONFIG:}"
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
      bindings:
        registryProducer-out-0:
          binder: kafka-registry-producer
          content-type: "\${KAFKA_CONTENT_TYPE:application/json}"
          destination: "\${KAFKA_TOPIC_REGISTRIES:p4pa-payhub-registries-evh}"
      kafka:
        binder:
          auto-create-topics: false
          configuration:
            heartbeat.interval.ms: "\${KAFKA_CONFIG_HEARTBEAT_INTERVAL_MS:3000}"
            session.timeout.ms: "\${KAFKA_CONFIG_SESSION_TIMEOUT_MS:30000}"
            request.timeout.ms: "\${KAFKA_CONFIG_REQUEST_TIMEOUT_MS:60000}"
            metadata.max.age.ms: "\${KAFKA_CONFIG_METADATA_MAX_AGE:180000}"
            sasl.mechanism: "\${KAFKA_CONFIG_SASL_MECHANISM:PLAIN}"
            security.protocol: "\${KAFKA_CONFIG_SECURITY_PROTOCOL:SASL_SSL}"
            max.request.size: "\${KAFKA_CONFIG_MAX_REQUEST_SIZE:1000000}"
        binders:
          registryProducer-out-0:
            producer:
              configuration:
                client.id: pu-sil
                connections.max.idle.ms: "\${KAFKA_REGISTRIES_PRODUCER_CONNECTION_MAX_IDLE_TIME:180000}"
                retry.backoff.ms: "\${KAFKA_REGISTRIES_PRODUCER_RETRY_MS:\${KAFKA_RETRY_MS:10000}}"
                linger.ms: "\${KAFKA_REGISTRIES_PRODUCER_LINGER_MS:\${KAFKA_LINGER_MS:2}}"
                batch.size: "\${KAFKA_REGISTRIES_PRODUCER_BATCH_SIZE:\${KAFKA_BATCH_SIZE:16384}}"

springwolf:
  docket:
    base-package: it.gov.pagopa.pu.sil.event
    info:
      title: "\${spring.application.name}"
      version: "\${spring.application.version}"
      description: AsyncAPI And Models
    servers.kafka-server:
      protocol: kafka
      host: "\${KAFKA_BINDER_BROKER:localhost:9093}"
  use-fqn: false

management:
  info:
    build.enabled: true
    java.enabled: true
    git.enabled: true
  tracing:
    baggage.remote-fields:
      - X-user-id
  observations:
    http.server:
        filter.order: -100
  endpoints:
    jmx:
      exposure.include: "*"
    web:
      exposure:
        include: health, info, prometheus, metrics, caches
      base-path: /actuator
  endpoint:
    health:
      probes.enabled: true
      logging.slow-indicator-threshold: "\${HEALTH_ACTUATOR_LOGGER_TIMEOUT_DURATION:PT1S}"
      show-details: "\${HEALTH_ACTUATOR_SHOW_DETAILS:when-authorized}"
      group:
        readiness.include: "*"
        liveness.include: livenessState,diskSpace,ping,binders
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${artifactId}
    export:
      prometheus:
        enabled: true
        step: 1m
        descriptions: true
    enable:
      jvm: true
      process: true
      system: true
      http: true
      logback: true

logging:
  level:
    root: "\${LOG_LEVEL_ROOT:INFO}"
    it.gov.pagopa: "\${LOG_LEVEL_PAGOPA:INFO}"
    org.springframework: "\${LOG_LEVEL_SPRING:INFO}"
    org.springframework.boot.availability: "\${LOG_LEVEL_SPRING_BOOT_AVAILABILITY:DEBUG}"
    org.springframework.kafka: "\${LOG_LEVEL_SPRING_KAFKA:INFO}"
    org.apache.kafka.clients.consumer.internals.ConsumerCoordinator: "\${LOG_LEVEL_KAFKA_CONSUMER_COORDINATOR:WARN}"
    it.gov.pagopa.pu.sil.exception.PuSilExceptionHandler: "\${LOGGING_LEVEL_API_REQUEST_EXCEPTION:INFO}"
    org.springdoc.core.utils.SpringDocAnnotationsUtils: "\${LOG_LEVEL_SPRING_DOC:ERROR}"
    PERFORMANCE_LOG: "\${LOG_LEVEL_PERFORMANCE_LOG:INFO}"
    PERFORMANCE_LOG.API_REQUEST: "\${LOG_LEVEL_PERFORMANCE_LOG_API_REQUEST:\${logging.level.PERFORMANCE_LOG}}"
    PERFORMANCE_LOG.REST_INVOKE: "\${LOG_LEVEL_PERFORMANCE_LOG_REST_INVOKE:\${logging.level.PERFORMANCE_LOG}}"

soap:
  sil:
    wsdl-base-url: "\${SIL_WSDL_BASE_URL:http://localhost:8080}"

rest:
  defaults:
    connection-pool:
      size: "\${DEFAULT_REST_CONNECTION_POOL_SIZE:10}"
      size-per-route: "\${DEFAULT_REST_CONNECTION_POOL_SIZE_PER_ROUTE:5}"
      time-to-live-minutes: "\${DEFAULT_REST_CONNECTION_POOL_TIME_TO_LIVE_MINUTES:10}"
    timeout:
      connect-millis: "\${DEFAULT_REST_TIMEOUT_CONNECT_MILLIS:120000}"
      read-millis: "\${DEFAULT_REST_TIMEOUT_READ_MILLIS:120000}"
  integrity-data:
    issuer: "\${REST_AGID_INTEGRITY_PU_ISSUER:piattaforma-unitaria}"
    private-key: "\${REST_AGID_INTEGRITY_PU_PRIVATEKEY:}"
    public-key: "\${REST_AGID_INTEGRITY_PU_PUBLICKEY:}"
    expirationMinutes: "\${REST_AGID_INTEGRITY_PU_EXPIRATION_MINUTES:10}"
  auth:
    base-url: "\${AUTH_SERVER_BASE_URL:}/payhub"
    max-attempts: "\${AUTH_MAX_ATTEMPTS:3}" # It's counting also the first attempt
    wait-time-millis: "\${AUTH_WAIT_TIME_MILLIS:500}"
    print-body-when-error: "\${AUTH_PRINT_BODY_WHEN_ERROR:true}"
  debt-position:
    base-url: "\${DEBT_POSITION_BASE_URL:}"
    max-attempts: "\${DEBT_POSITION_MAX_ATTEMPTS:3}" # It's counting also the first attempt
    wait-time-millis: "\${DEBT_POSITION_WAIT_TIME_MILLIS:500}"
    print-body-when-error: "\${DEBT_POSITION_PRINT_BODY_WHEN_ERROR:true}"
  fileshare:
    base-url: "\${FILESHARE_BASE_URL:}"
    max-attempts: "\${FILE_SHARE_MAX_ATTEMPTS:3}" # It's counting also the first attempt
    wait-time-millis: "\${FILE_SHARE_WAIT_TIME_MILLIS:500}"
    print-body-when-error: "\${FILE_SHARE_PRINT_BODY_WHEN_ERROR:true}"
  organization:
    base-url: "\${ORGANIZATION_BASE_URL:http://localhost:8081}"
    max-attempts: "\${ORGANIZATION_MAX_ATTEMPTS:3}" # It's counting also the first attempt
    wait-time-millis: "\${ORGANIZATION_WAIT_TIME_MILLIS:500}"
    print-body-when-error: "\${ORGANIZATION_PRINT_BODY_WHEN_ERROR:true}"
  send-notification:
    base-url: "\${SEND_NOTIFICATION_BASE_URL:}"
    max-attempts: "\${SEND_NOTIFICATION_MAX_ATTEMPTS:3}" # It's counting also the first attempt
    wait-time-millis: "\${SEND_NOTIFICATION_WAIT_TIME_MILLIS:500}"
    print-body-when-error: "\${SEND_NOTIFICATION_PRINT_BODY_WHEN_ERROR:true}"
  process-executions:
    base-url: "\${PROCESS_EXECUTIONS_BASE_URL:}"
    max-attempts: "\${PROCESS_EXECUTIONS_MAX_ATTEMPTS:3}" # It's counting also the first attempt
    wait-time-millis: "\${PROCESS_EXECUTIONS_WAIT_TIME_MILLIS:500}"
    print-body-when-error: "\${PROCESS_EXECUTIONS_PRINT_BODY_WHEN_ERROR:true}"
  pagopa-node-services:
    checkout:
      base-url: "\${PAGOPA_NODE_CHECKOUT_BASE_URL:}"
      max-attempts: "\${PAGOPA_NODE_CHECKOUT_MAX_ATTEMPTS:3}" # It's counting also the first attempt
      wait-time-millis: "\${PAGOPA_NODE_CHECKOUT_WAIT_TIME_MILLIS:500}"
      print-body-when-error: "\${PAGOPA_NODE_CHECKOUT_PRINT_BODY_WHEN_ERROR:true}"
  workflow-hub:
    base-url: "\${WORKFLOW_HUB_BASE_URL:http://localhost:8082}/workflowhub"
    max-attempts: "\${WORKFLOW_HUB_MAX_ATTEMPTS:3}" # It's counting also the first attempt
    wait-time-millis: "\${WORKFLOW_HUB_WAIT_TIME_MILLIS:500}"
    print-body-when-error: "\${WORKFLOW_HUB_PRINT_BODY_WHEN_ERROR:true}"
  actualization:
    max-attempts: "\${NOTIFICATION_PRICE_MAX_ATTEMPTS:3}" # It's counting also the first attempt
    wait-time-millis: "\${NOTIFICATION_PRICE_WAIT_TIME_MILLIS:500}"
    print-body-when-error: "\${NOTIFICATION_PRICE_PRINT_BODY_WHEN_ERROR:true}"
  payment-notification:
    max-attempts: "\${PAYMENT_NOTIFICATION_MAX_ATTEMPTS:3}" # It's counting also the first attempt
    wait-time-millis: "\${PAYMENT_NOTIFICATION_WAIT_TIME_MILLIS:500}"
    print-body-when-error: "\${PAYMENT_NOTIFICATION_PRINT_BODY_WHEN_ERROR:true}"
  classification:
    base-url: "\${CLASSIFICATION_BASE_URL:}"
    max-attempts: "\${CLASSIFICATION_MAX_ATTEMPTS:3}" # It's counting also the first attempt
    wait-time-millis: "\${CLASSIFICATION_WAIT_TIME_MILLIS:500}"
    print-body-when-error: "\${CLASSIFICATION_PRINT_BODY_WHEN_ERROR:true}"
  pagopa-payments:
    base-url: "\${PAGOPA_PAYMENTS_BASE_URL:}"
    max-attempts: "\${PAGOPA_PAYMENTS_MAX_ATTEMPTS:3}" # It's counting also the first attempt
    wait-time-millis: "\${PAGOPA_PAYMENTS_WAIT_TIME_MILLIS:500}"
    print-body-when-error: "\${PAGOPA_PAYMENTS_PRINT_BODY_WHEN_ERROR:true}"

legacy-auth:
  basic-legacy-expiration-seconds: "\${BASIC_LEGACY_AUTH_EXPIRATION_TIMEOUT_SECONDS:300}" # 5 minutes
  jwt-legacy-expiration-seconds: "${JWT_LEGACY_AUTH_EXPIRATION_TIMEOUT_SECONDS:3600}" # 1 hour

public-base-url:
  fileshare: "\${PUBLIC_BASE_URL_FILESHARE:}"
  pu-sil: "\${PUBLIC_BASE_URL_PU_SIL:}"

springdoc:
  writer-with-default-pretty-printer: true

checkout:
  default-callback-url:
    ok: "\${CHECKOUT_DEFAULT_CALLBACK_URL_OK:http://localhost:8080/checkout/ok}"
    ko: "\${CHECKOUT_DEFAULT_CALLBACK_URL_KO:http://localhost:8080/checkout/ko}"
    cancel: "\${CHECKOUT_DEFAULT_CALLBACK_URL_CANCEL:http://localhost:8080/checkout/cancel}"

cache:
  debtPositionTypeOrg:
    size: "\${CACHE_DEBTPOSITION_TYPE_ORG_SIZE:1000}"
    expire-in: "\${CACHE_DEBTPOSITION_TYPE_ORG_MINUTES:60}"
  debtPositionType:
    size: "\${CACHE_DEBTPOSITION_TYPE_SIZE:100}"
    expire-in: "\${CACHE_DEBTPOSITION_TYPE_MINUTES:60}"
  organization:
    size: "\${CACHE_ORGANIZATION_SIZE:1000}"
    expire-in: "\${CACHE_ORGANIZATION_MINUTES:60}"
  taxonomy:
    size: "\${CACHE_TAXONOMY_SIZE:100}"
    expire-in: "\${CACHE_TAXONOMY_MINUTES:60}"
