server:
  http: "\${SERVER_PORT:8080}"

spring:
    application:
      name: ${artifactId}
      version: ${version}
    jmx.enabled: true
    threads:
      virtual:
        enabled: "\${VIRTUAL_THREADS_ENABLED:true}"

management:
    endpoints:
      jmx:
        exposure.include: "*"
      web:
        exposure:
          include: health, info, prometheus, metrics
        base-path: /actuator
    endpoint:
      health:
        probes.enabled: true
        group:
          readiness.include: "*"
          liveness.include: livenessState,diskSpace,ping
      prometheus:
        enabled: true
    metrics:
      tags:
        application: ${artifactId}
      export:
        prometheus:
          enabled: true
          step: 1m
          descriptions: true
      enable:
        jvm: true
        process: true
        system: true
        http: true
        logback: true
