package it.gov.pagopa.pu.sil.connector.pagopa.checkout.client;

import it.gov.pagopa.nodo.checkout.controller.ApiClient;
import it.gov.pagopa.nodo.checkout.controller.generated.DefaultApi;
import it.gov.pagopa.nodo.checkout.dto.generated.CartRequest;
import it.gov.pagopa.pu.sil.config.rest.RestTemplateConfig;
import it.gov.pagopa.pu.sil.connector.pagopa.checkout.config.CheckoutApiClientConfig;
import it.gov.pagopa.pu.sil.util.StatusModifyingClientHttpResponseWrapper;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.restclient.RestTemplateBuilder;
import org.springframework.http.HttpRequest;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.http.client.ClientHttpRequestExecution;
import org.springframework.http.client.ClientHttpRequestInterceptor;
import org.springframework.http.client.ClientHttpResponse;
import org.springframework.http.client.SimpleClientHttpRequestFactory;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;

@Service
@Slf4j
public class CheckoutClient {

  private final DefaultApi checkoutApiClient;

  static final HttpStatus FAKE_REDIRECT_STATUS = HttpStatus.IM_USED; // 226 IM Used is used to indicate a redirect in this context



  public CheckoutClient(CheckoutApiClientConfig clientConfig,
                        RestTemplateBuilder restTemplateBuilder) {

    RestTemplate restTemplate = restTemplateBuilder.build();

    /*
     * The following customizations of RestTemplate are needed to overcome the bad handling of redirect responses
     * on autogenerated code by Openapi-generator (see also https://github.com/OpenAPITools/openapi-generator/issues/5397).
     *
     * The interceptor modifies the response status code to a 2xx one [HttpStatus.IM_USED (226)] when it is 3xx redirection...
     */
    List<ClientHttpRequestInterceptor> newInterceptors = new ArrayList<>(restTemplate.getInterceptors());
    newInterceptors.add(this::redirectInterceptor);
    restTemplate.setInterceptors(newInterceptors);

    //... and the custom request factory disables automatic redirects, allowing this class to handle them (and return the redirect url).
    restTemplate.setRequestFactory(new SimpleClientHttpRequestFactory() {
      @Override
      protected void prepareConnection(HttpURLConnection connection, String httpMethod) throws IOException {
        super.prepareConnection(connection, httpMethod);
        connection.setInstanceFollowRedirects(false);
      }
    });

    if (clientConfig.isPrintBodyWhenError()) {
      restTemplate.setErrorHandler(RestTemplateConfig.bodyPrinterWhenError("PAGOPA-CHECKOUT"));
    }

    ApiClient apiClient = new ApiClient(restTemplate);
    apiClient.setBasePath(clientConfig.getBaseUrl());
    apiClient.setMaxAttemptsForRetry(Math.max(1, clientConfig.getMaxAttempts()));
    apiClient.setWaitTimeMillis(clientConfig.getWaitTimeMillis());
    this.checkoutApiClient = new DefaultApi(apiClient);
  }

  ClientHttpResponse redirectInterceptor(HttpRequest request, byte[] body, ClientHttpRequestExecution execution) throws IOException {
    ClientHttpResponse response = execution.execute(request, body);
    if (response.getStatusCode().is3xxRedirection()) {
      StatusModifyingClientHttpResponseWrapper modifiedResponse = new StatusModifyingClientHttpResponseWrapper(response);
      modifiedResponse.setStatusCode(FAKE_REDIRECT_STATUS);
      response = modifiedResponse;
    }
    return response;
  }

  public String checkoutCart(CartRequest cartRequest) {
    ResponseEntity<Void> responseEntity = this.checkoutApiClient.postCartsWithHttpInfo(cartRequest);
    URI location = null;
    if (responseEntity.getStatusCode().equals(FAKE_REDIRECT_STATUS)) {
      location = responseEntity.getHeaders().getLocation();
    }
    return location != null ? location.toString() : null;
  }

}
